apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: host-pvc
spec:
  volumeName: host-pv
  accessMode:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi