apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: first-app
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 8080
  type: LoadBalancer
  ---
  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: first-app
      tier: backend
  template:
    metadata:
      labels:
        app: first-app
        tier: backend
    spec:
      containers: 
        - name: kub-first-app
          image: naan709/kub-first-app